version: '3'
services:
  survey:
    build: .
    volumes: 
      - .:/usr/src/survey
    environment:
      - PYTHONUNBUFFERED=TRUE
  nginx:
    image: "nginx"
    command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/survey.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - SERVER_NAME=experimentgoal.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on: 
      - survey
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"